## (발신 채널) SendChannel <in E>

- `Channel`에 데이터를 보내는 Sender의 인터페이스
- SendChannel과 ReceiveChannel을 결합하여 완전한 Channel 인터페이스가 정의된다.
- 직접 이 인터페이스를 구현해서 쓸일은 거의 없고, 채널 구현체 [Channel]을 사용하거나, [Channel]에 위임해서 사용한다.

### (더이상 보낼 수 없나요?) val isClosedForSend: Boolean

- Channel이 `close`호출로 닫혔거나, Receive 쪽이 `cancelled`된 경우 `true`를 반환한다.

  → `true`인 상태에서 send를 호출하면 예외가 발생한다는 뜻이다.

- 주의! 이 속성이 `false`를 리턴하더라도, 직후 send 호출이 성공할 것을 보장하지 않는다.

  → (확인 직후 채널이 동시에 close될 수도 있기 때문)

  ⇒ `trySend`가 더 안정적인 해결책이다.

  → 요소 send를 시도하고 “channel이 닫혔는지 여부”

    + 닫히지 않았다면 ⇒ “값 전송이 성공했는지 여부”를 알려주는 결과를 반환한다.

    ```kotlin
    // 위험! 신뢰할 수 없음!
    if (!channel.isClosedForSend) {
        channel.send(element) // 여전히 실패할 수도 있음
    } else {
        println("Can not send: the channel is closed")
    }
    // 이렇게 사용하세요:
    channel.trySend(element).onClosed {
        println("Can not send: the channel is closed")
    }
    ```

- 이 속성의 주요 용도는 Channel이 이미 닫혔을 때 코드 일부분을 실행하지 않고 건너뛰는 것이다.

    ```kotlin
    if (channel.isClosedForSend) {
       // fast path (계산 skip)
       return
    } else {
       // slow path: 실제 값 연산
       val nextElement = run {
           // 무거운 작업
       }
       channel.send(nextElement) // 실패할 수도있음 (보장되지 않기 때문),
       // 하지만 적어도 계산을 피하려고 노력했음
    }
    ```

- 그러나, 대부분의 경우 send할 요소를 생성하는 코루틴을 취소하는 것이 더 일반적인 방법이다.
- `produce`는 “요소를 생성”하고 + “채널이 닫히면 스스로 취소”하는 코루틴을 실행하는 방법이다.
- 채널의 상태를 확인하기 위한 어설션과 진단에서도 사용할 수 있다.

### (보내기) suspend fun send(element: E)

- 지정된 요소를 채널로 보낸다.
- 일시중단 될 수 있는 경우

  → 채널의 버퍼로 보내지 못했을 때 (버퍼가 없는 경우는 수신측에 직접 전달하지 못했을 때)

- 성공적으로 요소를 전달 했는지 여부와 관계 없이 취소될 수 있다.
- 채널이 closed된 경우 예외를 던진다.

> 일시중단과 취소
>
- BufferOverflow 전략이 Suspend인 경우 → 일시중단 될 수 있다.
- 정확한 시나리오는 capacity에 따라 다르다
    - capacity = rendezvous 인 경우

      → sender는 receiver가 호출될 때까지 일시 중단된다.

    - capacity = unlimited or conflated 인 경우

      → sender는 절대 일시중단되지 않는다. (suspend 전략이여도)

    - capacity = buffered (기본값 아닌경우도) 인 경우

      → sender는 버퍼 빈 공간이 생길 때까지 일시 중단된다.


- 취소 가능하다.

  → 함수가 일시 중단된 동안 현재 코루틴의 Job이 cancelled 되면 → 즉시 CancellationException과함께 재개된다.

- 즉각적인 취소가 보장된다.

  send가 요소를 보냈더라도, 일시 중단 중에 cancelled되면 → CancellationException을 던진다

- 즉시 취소 보장으로 → 예외가 항상 요소전달이 실패했다는 것을 의미하지 않는다.

  (전달되지 않은 요소를 처리하는 세부사항은 UnDeliveredElement 문서확인)

- 일시중단이 아닐 때는 취소를 확인하지 않는다.

  필요한 경우 `ensureActive`나 CoroutineScope.`isActive`를 사용해서 주기적으로 취소 여부를 확인해라

    ```kotlin
    // because of UNLIMITED, sending to this channel never suspends
    val channel = Channel<Int>(Channel.UNLIMITED)
    val job = launch {
        while (isActive) {
            channel.send(42)
        }
        // the loop exits when the job is cancelled
    }
    ```

    - 루프 내부에서 delay같은 취소가능한 함수가 호출된다면 isActive를 사용하지 않아도 된다. (delay가 취소를 확인하기 때문)

> 닫힌 채널로 보내기
>
- send가 호출되기전에 채널이 closed되고 cause가 지정되지 않았다면

  → send에서 ClosedSendChannelException(닫힌 발신 채널 예외)이 발생한다.

- send가 호출되기전에 채널이 cause와 함께 closed됐다면

  → send는 close에 전달된 것과 동일한(===) 예외를 다시 발생시킨다.

- 두 경우 모두 소비자에게 요소가 전달되지 않았음을 보장하고, onUndeliveredElement 콜백이 호출된다.
- send가 일시중단된 이후 channel을 닫는 것은 → 중단된 send호출이 종료되는 원인이 되지 않는다.

  (channel이 닫힌 직후 send호출은 실패하지만, 기존의 호출은 sending 코루틴이 cancelled되지 않는 이상 완료까지 계속 진행된다.


> 관련 내용
>
- select 호출에서 onSend 절과 함께 사용 가능
- 대기 없이, 예외 없이 채널로 요소를 보내고 싶다면 `trySend`를 사용해라.

### (select에서 send) val onSend: SelectClause2<E, SendChannel<E>>

- send 함수의 select 표현식에 대한 절이다.
- 매개변수로 지정된 요소가 채널로 전송될 때 호출된다.
    - 절이 선택되면 → 해당 블럭으로 이 채널에 대한 참조가 전달된다.

---

- select가 일시중단되기 전에 채널이 isClosedForSend == true 인 경우 select 호출은 예외와 함께 실패한다. (닫힌 채널로 전송)

---

- select 표현식은 정확히 하나의 요소가 수신자에게 보내질 때까지 대기한다.

  → 나머지 채널들은 onUndeliveredElement 콜백을 호출한다.

- send와 마찬가지로, onSend는 즉시 취소 규칙을 따른다

  → select가 요소를 성공적으로 보냈더라도 CancellationException으로 종료될 수 있다.


### (예외 없이 즉시 보내기) fun trySend(element: E): ChannelResult<Unit>

- 지정된 요소를 대기없이 채널에 추가하려고 시도
- 절대 suspend 되지 않고, 예외를 던지지 않는다.

  → 대신에 작업 결과를 캡슐화한 ChannelResult를 반환한다.

  (일시중단되고, 예외를 던질 수 있는 send와 다르다)


---

- 채널이 닫혀있거나, 꽉차서 채널이 새로운 요소들을 더이상 받을 수 없을 때

  → 실패를 나타내는 ChannelResult.isFailure를 반환한다.

  (이 경우, 요소가 소비자에게 전달되지 않았음이 보장된다.

  → 채널에서 onUndeliveredElement 콜백이 제공된 경우 호출되지 않는다. [send자체가 되지 않았으니깐] )


---

- 채널의 버퍼가 overflow될 수 없다는것을 미리 알고 있는 경우

  → send의 대신 일시중단하지 않는 trySend를 사용할 수 있다.

    ```kotlin
    class Coordinates(val x: Int, val y: Int)
    // A channel for a single subscriber that stores the latest mouse position update.
    // If more than one subscriber is expected, consider using a `StateFlow` instead.
    val mousePositionUpdates = Channel<Coordinates>(Channel.CONFLATED)
    // Notifies the subscriber about the new mouse position.
    // If the subscriber is slow, the intermediate updates are dropped.
    fun moveMouse(coordinates: Coordinates) {
        val result = mousePositionUpdates.trySend(coordinates)
        if (result.isClosed) {
            error("Mouse position is no longer being processed")
        }
    }
    ```


### (채널 닫기 + 기존 요소 유지) fun close(cause: Throwable? = null): Boolean

- 채널을 닫는다 → 이후 send는 실패한다.

---

- 채널이 이미 닫혀있지 않고, 이 함수 호출로 채널이 닫힌 경우 → true 반환
- 채널이 이미 닫혀있으면 → 이 함수는 아무것도 하지 않고 → false 반환

---

- 채널에 남아있는 기존 요소들은 그대로 유지된다.

  (close 호출전에 일시중단된 send, onSend 호출도 영향을 받지 않는다.)

    - close 호출 이후의 send, trySend, onSend 호출만 실패한다.
    - isClosedForSend는 close가 호출 직후부터 true를 반환하기 시작한다.
- 기존 요소가 모두 수신되면, 채널은 수신도 닫힌것으로 간주한다.

  → receive가 예외를 던지기 시작한다는 의미 (isClosedForReceive 가 true를 반환하기 시작함)


---

- close의 `cause`가 null이 아닌 경우

  → 이후 모든 send 시 `cause`를 던진다.

  → 요소가 더이상 남아있지 않은 상태에서 receive를 시도할 때 `cause`를 던진다.

- close의 `cause`가 null인 경우 → 채널은 정상적으로 완료된것으로 간주

  → 이후 모든 `send` 호출은 `ClosedSendChannelException`을 던진다.

  → 요소가 더이상 남아있지 않은 상태에서 `receive`를 시도할 때 `ClosedReceiveChannelException`을 던진다.


### (닫혔을 때 호출) fun invokeOnClose(handler: (cause: Throwable?) → Unit)

- 채널이 closed되거나, 수신측 채널이 cancelled되면 → 동기적으로 한번만 호출되는 handler 등록
- 채널의 수명동안 하나의 handler만 추가할 수 있다.
- isClosedForSend가 true를 반환하기 시작할때 핸들러가 호출된다.
- 채널이 이미 닫혀있다면 핸들러는 즉시 호출된다.

---

- handler로 전달되는 cause의 의미
    - 채널이 정상적으로 cause = null로 닫혔을 때 → null
    - 채널이 인자없이 정상적으로 취소된경우 → CancellationException
    - 그외의 경우 → close 또는 cancel의 cause

---

> 실행 컨텍스트와 예외 안전성
>
- 핸들러는 closing과 cancelling 작업의 일부이며, 채널이 최종상태에 도달한 후에만 실행된다.

  → 따라서, 핸들러가 예외를 던지거나 멈추더라도 채널은 여전히 성공적으로 closed, cancelled 된다는 것을 의미한다.

- 핸들러에서 처리되지 않은 예외는 closing, cancelling 작업을 호출한 쪽으로 전파된다.

> 안정성 주의!
>
- 이 함수는 안정적인 API를 구성하지만, 하나의 예외를 가지고 있다.

  → 여러개의 핸들러가 등록될 때 ⇒ IllegalStateException을 발생시킨다. (이 제한은 향후 제거될 수 있다.)


> Throws
>
- IllegalStateException → 다른 핸들러가 이미 등록된 경우
- UnsupportedOperationException → 기본 채널이 invokeOnClose를 지원하지 않는경우 (현재는 Rx- 와의 통합에서만 지원되지 않는다.)